version: '{branch}-{build}'

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
          JAVA_HOME: C:\Program Files\Java\jdk17
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          JAVA_HOME: /usr/lib/jvm/jdk15

# A note/reminder for readers: Script items prefixed "cmd:" are executed on Windows-only environments.
# Items with no prefix are run on all environments (Windows & Linux)

init:
    - cmd: git config --global core.autocrlf true
    
install:
    - git submodule update --init --recursive
    - cmd: dotnet tool install --global dotnet-sonarscanner
    
before_build:
    - dotnet --version
    - dotnet restore --verbosity m
    - cmd: >
        IF NOT DEFINED APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH (SET BranchName=%APPVEYOR_REPO_BRANCH%)
        ELSE (SET BranchName=%APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH%)
    - cmd: >
        dotnet-sonarscanner begin 
        /k:"Autofac.DecoratorBuilder"
        /v:AppVeyor_build_%APPVEYOR_BUILD_NUMBER%
        /o:craigfowler-github
        /d:sonar.host.url="https://sonarcloud.io"
        /d:sonar.login=%SONARCLOUD_SECRET_KEY%
        /d:sonar.cs.nunit.reportsPaths=%APPVEYOR_BUILD_FOLDER%\CSF.DecoratorBuilder.Tests\TestResults\TestResults.xml
        /d:sonar.cs.opencover.reportsPaths=%APPVEYOR_BUILD_FOLDER%\CSF.DecoratorBuilder.Tests\TestResults\coverage.opencover.xml
        /d:sonar.branch.name=%BranchName%
        /s:%APPVEYOR_BUILD_FOLDER%\.sonarqube-analysisproperties.xml

build_script:
    - dotnet build

test_script:
    - >
        dotnet test
        -c Autofac_62
        /p:CollectCoverage=true
        /p:CoverletOutputFormat=\"json,opencover\"
        /p:CoverletOutput=\"TestResults/\"
        --test-adapter-path:.
        --logger:\"nunit\"

    - dotnet test -c Autofac_51
    - dotnet test -c Autofac_50
    - dotnet test -c Autofac_49
    - dotnet test -c Autofac_42

after_test:
    - cmd: >
        dotnet-sonarscanner end
        /d:"sonar.login=%SONARCLOUD_SECRET_KEY%"

